services:
  - type: web
    name: scrum-poker-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
